name: Debug APK Builder

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout manage-keystore repo
        uses: actions/checkout@v2
        with:
          token: ${{ steps.generate_token.outputs.token }}
          repository: "futchiis/manage-keystore"
          path: "keystore"

      - name: Prepare files for signing
        run: cp keystore/futchiis.jks app/

      - name: Grant rights
        run: chmod +x ./gradlew

      - name: Build debug APK with Gradle
        run: source keystore/env && ./gradlew --warning-mode all assemble

      - name: Upload Debug
        uses: actions/upload-artifact@v2
        with:
          name: 'build'
          path: app/build/outputs/apk/debug/app-debug.apk
